export const colonies = [
    {topic: '2000', name: '2000'},
    { topic: '30_mayo', name:'30 de Mayo'},
    { topic: '7_enero', name:'7 de Enero'},
    { topic: 'alamos', name:'Álamos'},
    { topic: 'anahuac', name:'Anáhuac'},
    { topic: 'aquiles_serdan', name:'Aquiles Serdán'},
    { topic: 'arboledas', name:'Arboledas'},
    { topic: 'aurora', name:'Aurora'},
    { topic: 'balastrera', name:'Balastrera'},
    { topic: 'carranza', name:'Carranza'},
    { topic: 'chapultepec', name:'Chapultepec'},
    { topic: 'corregidora', name:'Corregidora'},
    { topic: 'el_aguila', name:'El Águila'},
    { topic: 'el_arenal', name:'El Arenal'},
    { topic: 'el_cerrito', name:'El Cerrito'},
    { topic: 'encinar', name:'Encinar'},
    { topic: 'carrillo_puerto', name:'Carrillo Puerto'},
    { topic: 'guerrero', name:'Guerrero'},
    { topic: 'la_carbonera', name:'La Carbonera'},
    { topic: 'libertad', name:'Libertad'},
    { topic: 'lopez_arias', name:'Lopez Arias'},
    { topic: 'los_fresnos', name:'Los Fresnos'},
    { topic: 'mirador', name:'Mirador'},
    { topic: 'nogales_centro', name:'Nogales Centro'},
    { topic: 'nueva_rosita', name:'Nueva Rosita'},
    { topic: 'ojo_zarco', name:'Ojo Zarco'},
    { topic: 'paseo_nuevo', name:'Paseo Nuevo'},
    { topic: 'provincia', name:'Provincia'},
    { topic: 'reforma', name:'Reforma'},
    { topic: 'taza_agua', name:'Taza de Agua'},
    { topic: 'union_progreso', name:'Unión y Progreso'},
    { topic: 'vista_hermosa', name:'Vista Hermosa'},
]
